CC=gcc
CCFLAGS=-Wall

echo:
	$(CC) $(CCFLAGS) -o TCPEchoClient4 TCPEchoClient4.c

get_proto_by_name:
	$(CC) $(CCFLAGS) -o get_proto_by_name get_proto_by_name.c

clean:
	rm TCPEchoClient4 get_proto_by_name

