CC=gcc
CCFLAGS=-Wall

echo:
	$(CC) $(CCFLAGS) -o TCPEchoClient4 TCPEchoClient4.c

get_proto_by_name:
	$(CC) $(CCFLAGS) -o get_proto_by_name get_proto_by_name.c

socket_example_2:
	$(CC) $(CCFLAGS) -o socket_example_2 socket_example_2.c

clean:
	rm TCPEchoClient4 get_proto_by_name socket_example_2

